# Configuration file for all common and default values.
spring:
  application:
    name: flights-status-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    defer-datasource-initialization: true
  h2:
    console.enabled: true

server:
  port: 6789
